filter: 'process.command_line: "*mask*hybrid-sleep.target*"'
pre_detector:
  case_condition: directly
  id: c172b7b5-f3a1-4af2-90b7-822c63df86cb
  mitre:
  - attack.persistence
  - attack.impact
  - attack.t1653
  severity: high
  title: Mask System Power Settings Via Systemctl
sigma_fields: true
description: 'Detects the use of systemctl mask to disable system power management
  targets such as suspend, hibernate, or hybrid sleep.

  Adversaries may mask these targets to prevent a system from entering sleep or shutdown
  states, ensuring their malicious processes remain active and uninterrupted.

  This behavior can be associated with persistence or defense evasion, as it impairs
  normal system power operations to maintain long-term access or avoid termination
  of malicious activity.

  '
